### ISSUE TITLE
Atom s3 lite

### ISSUE THREAD

**Issue by dirksenrdh** [tieskuh/esphome-comfoair#6]
I am trying to run this program on a Atom s3 lite.
 this is the code

```
esphome:
  name: esphome-web-962858
  friendly_name: ESP WHR930
  min_version: 2024.11.0
  name_add_mac_suffix: false
  
  on_boot:
    priority: 300
    then:
      lambda: |-
        #include "WiFi.h"
        #include "esp_wifi.h"
        esp_wifi_set_protocol(WIFI_IF_STA, WIFI_PROTOCOL_11B | WIFI_PROTOCOL_11G);

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: "SSID"
  password: password
  manual_ip:
    static_ip: x.y.z.74
    gateway: x.y.z.1
    subnet: 255.255.255.0
    
web_server: # creates a web server where you can access all this stuff without home assistant (good for debugging or working headless (no HA))
  version: 3
  port: 80
  include_internal: true
  ota: true

external_components:
  - source:
      type: git
      url: https://github.com/tieskuh/esphome-comfoair
    components: [comfoair]
    refresh: 0s
```

it looks like the external component is not compatible with the Atom s3 lite because I get this error while compiling:

```
Linking .pioenvs/esphome-web-962858/firmware.elf
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
*** [.pioenvs/esphome-web-962858/firmware.elf] Error 1
========================= [FAILED] Took 24.06 seconds =========================
```

what could be the solution?

**Comment by tieskuh** [comment]
I don't think it has anything to do with the external component.
Can you try to compile without external_components and try if it does compile without?

**Comment by dirksenrdh** [comment]
it compiles without problems if I don't include the external component.
there is a board difference between de old Atom light (eps8266 based) and the new Atom s3 light (ESP32 based).
may be there are some references to the board in the scripts referring to the 8266 board which not will work with a ESP32 board.

BTW I installed your software (as a test) on a standard esp8266 (not atom) and there I met no problems at all. all the sensors appeared in my HA environment. that is another reason I suspect it to be board related.

**Comment by tieskuh** [comment]
To be sure: did you also include the rest of the code?

```

uart:
  id: uart_bus
  rx_pin: 22
  tx_pin: 19
  baud_rate: 9600

comfoair:
  name: "WHR 950"
  uart_id: uart_bus
  fan_supply_air_percentage:
    name: "Supply fan"
  fan_exhaust_air_percentage:
    name: "Exhaust fan"
  fan_speed_supply:
    name: "Supply fan speed"
  fan_speed_exhaust:
    name: "Exhaust fan speed"
  is_bypass_valve_open:
    name: "Bypass"
  is_preheating:
    name: "Preheating"
  outside_air_temperature:
    name: "Outside temperature"
  supply_air_temperature:
    name: "Supply temperature"
  return_air_temperature:
    name: "Return temperature"
  exhaust_air_temperature:
    name: "Exhaust temperature"
  is_supply_fan_active:
    name: "Supply fan"
  is_filter_full:
    name: "Filter status"
  bypass_step:
    name: "Bypass valve"
  is_summer_mode:
    name: "Summer mode"

button:
  - platform: template
    name: "Reset filter"
    on_press:
      then:
        - lambda: |-
              id(comfoair_climate)->reset_filter();

```

I don't have an Atom S3 lite so I cannot reproduce it. I can try to run on another S3 device to check if I can reproduce it that way.
